import "../loadEnv.js";
import connectDB from "../db/config.js";
import Medicine from "../models/Medicine.model.js";

const medicines = [
  {
    name: "Panadl 500mg",
    genericName: "Paracetamol",
    manufacturer: "GSK",
    category: "Pain Relief",
    purchasePrice: 35,
    sellingPrice: 50,
    stock: 100,
    minimumStock: 20,
    isActive: true,
  },
  {
    name: "Brfen 400mg",
    genericName: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Pain Relief",
    purchasePrice: 45,
    sellingPrice: 65,
    stock: 75,
    minimumStock: 15,
    isActive: true,
  },
  {
    name: "Augmentin 625mg",
    genericName: "Amoxicillin + Clavulanic Acid",
    manufacturer: "GSK",
    category: "Antibiotic",
    purchasePrice: 180,
    sellingPrice: 220,
    stock: 50,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Cetrizine 10mg",
    genericName: "Cetirizine",
    manufacturer: "Getz Pharma",
    category: "Allergy",
    purchasePrice: 25,
    sellingPrice: 40,
    stock: 60,
    minimumStock: 15,
    isActive: true,
  },
  {
    name: "Disprin",
    genericName: "Aspirin",
    manufacturer: "Reckitt",
    category: "Pain Relief",
    purchasePrice: 20,
    sellingPrice: 30,
    stock: 80,
    minimumStock: 20,
    isActive: true,
  },
  {
    name: "Flagyl 400mg",
    genericName: "Metronidazole",
    manufacturer: "Sanofi",
    category: "Antibiotic",
    purchasePrice: 40,
    sellingPrice: 55,
    stock: 45,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Brufen 200mg",
    genericName: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Pain Relief",
    purchasePrice: 30,
    sellingPrice: 45,
    stock: 90,
    minimumStock: 20,
    isActive: true,
  },
  {
    name: "Risek 20mg",
    genericName: "Omeprazole",
    manufacturer: "Getz Pharma",
    category: "Gastric",
    purchasePrice: 60,
    sellingPrice: 80,
    stock: 40,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Losec 20mg",
    genericName: "Omeprazole",
    manufacturer: "AstraZeneca",
    category: "Gastric",
    purchasePrice: 75,
    sellingPrice: 100,
    stock: 35,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Flagyl 200mg",
    genericName: "Metronidazole",
    manufacturer: "Sanofi",
    category: "Antibiotic",
    purchasePrice: 25,
    sellingPrice: 35,
    stock: 30,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Amoxil 500mg",
    genericName: "Amoxicillin",
    manufacturer: "GSK",
    category: "Antibiotic",
    purchasePrice: 90,
    sellingPrice: 115,
    stock: 55,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Klaricid 500mg",
    genericName: "Clarithromycin",
    manufacturer: "Abbott",
    category: "Antibiotic",
    purchasePrice: 140,
    sellingPrice: 175,
    stock: 25,
    minimumStock: 8,
    isActive: true,
  },
  {
    name: "Voltaren 50mg",
    genericName: "Diclofenac",
    manufacturer: "Novartis",
    category: "Pain Relief",
    purchasePrice: 55,
    sellingPrice: 75,
    stock: 65,
    minimumStock: 15,
    isActive: true,
  },
  {
    name: "Ponstan 500mg",
    genericName: "Mefenamic Acid",
    manufacturer: "Pfizer",
    category: "Pain Relief",
    purchasePrice: 50,
    sellingPrice: 70,
    stock: 45,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Loprin 75mg",
    genericName: "Aspirin",
    manufacturer: "Sami Pharma",
    category: "Cardiovascular",
    purchasePrice: 20,
    sellingPrice: 30,
    stock: 70,
    minimumStock: 15,
    isActive: true,
  },
  {
    name: "Lasix 40mg",
    genericName: "Furosemide",
    manufacturer: "Sanofi",
    category: "Cardiovascular",
    purchasePrice: 30,
    sellingPrice: 45,
    stock: 22,
    minimumStock: 8,
    isActive: true,
  },
  {
    name: "Norvasc 5mg",
    genericName: "Amlodipine",
    manufacturer: "Pfizer",
    category: "Blood Pressure",
    purchasePrice: 45,
    sellingPrice: 65,
    stock: 50,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Cozaar 50mg",
    genericName: "Losartan",
    manufacturer: "Organon",
    category: "Blood Pressure",
    purchasePrice: 60,
    sellingPrice: 85,
    stock: 40,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Glucophage 500mg",
    genericName: "Metformin",
    manufacturer: "Merck",
    category: "Diabetes",
    purchasePrice: 35,
    sellingPrice: 50,
    stock: 85,
    minimumStock: 20,
    isActive: true,
  },
  {
    name: "Diamicron 80mg",
    genericName: "Gliclazide",
    manufacturer: "Servier",
    category: "Diabetes",
    purchasePrice: 70,
    sellingPrice: 95,
    stock: 28,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Ventolin Inhaler",
    genericName: "Salbutamol",
    manufacturer: "GSK",
    category: "Respiratory",
    purchasePrice: 90,
    sellingPrice: 120,
    stock: 32,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Surbex Z",
    genericName: "Multivitamins",
    manufacturer: "Abbott",
    category: "Vitamins",
    purchasePrice: 100,
    sellingPrice: 135,
    stock: 48,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Neurobion",
    genericName: "Vitamin B Complex",
    manufacturer: "Merck",
    category: "Vitamins",
    purchasePrice: 80,
    sellingPrice: 110,
    stock: 38,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Calpol 120mg",
    genericName: "Paracetamol",
    manufacturer: "GSK",
    category: "Pain Relief",
    purchasePrice: 45,
    sellingPrice: 60,
    stock: 5,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Brufen Syrup",
    genericName: "Ibuprofen",
    manufacturer: "Abbott",
    category: "Pain Relief",
    purchasePrice: 55,
    sellingPrice: 75,
    stock: 0,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Amoxil 250mg",
    genericName: "Amoxicillin",
    manufacturer: "GSK",
    category: "Antibiotic",
    purchasePrice: 55,
    sellingPrice: 75,
    stock: 7,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Omeprazole 20mg",
    genericName: "Omeprazole",
    manufacturer: "Sami Pharma",
    category: "Gastric",
    purchasePrice: 40,
    sellingPrice: 60,
    stock: 0,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Loratadine 10mg",
    genericName: "Loratadine",
    manufacturer: "Searle",
    category: "Allergy",
    purchasePrice: 30,
    sellingPrice: 45,
    stock: 12,
    minimumStock: 15,
    isActive: true,
  },
  {
    name: "Hydryllin Syrup",
    genericName: "Diphenhydramine",
    manufacturer: "Sami Pharma",
    category: "Cough & Cold",
    purchasePrice: 50,
    sellingPrice: 70,
    stock: 3,
    minimumStock: 10,
    isActive: true,
  },
  {
    name: "Benadryl Syrup",
    genericName: "Diphenhydramine",
    manufacturer: "Johnson & Johnson",
    category: "Cough & Cold",
    purchasePrice: 65,
    sellingPrice: 90,
    stock: 0,
    minimumStock: 10,
    isActive: true,
  },
];

const seedMedicines = async () => {
  try {
    await connectDB();

    await Medicine.insertMany(medicines);

    console.log(`✅ ${medicines.length} medicines added successfully`);

    process.exit(0);
  } catch (error) {
    console.error("❌ Failed to seed medicines:", error);
    process.exit(1);
  }
};

seedMedicines();